name: 'Run tests'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update
      run: sudo apt update
    - name: Install apt dependencies
      run: sudo apt install python3.8 python3-pip python3-setuptools python-wheel-common
    - name: Install requirements
      run: python3.8 -m pip install -r requirements.txt
    - name: Run tests
      run: python3.8 -m pytest
      timeout-minutes: 5
